name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build step 
        uses: denoland/setup-deno@v1 
          with:
            deno-version: vx.x.x
        run: deno check src/index.ts # 📝 Update the build command(s)

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "ich1fx-kit"
          entrypoint: "src/index.ts" # 📝 Update the entrypoint
          root: "."
